---
- summary: |
    При обновлении страницы сайта появляются ошибки загрузки
  environment: |
    Google Chrome	128.0.6613.138 (Официальная сборка) (64 бит)
    ОС Windows 11
  steps-to-reproduce: |
    1. Зайти на страницу магазина
    2. Открыть DevTools 
    3. Обновить страницу
    4. Перейти в Console
  expected-result: |
    Страница обновляется без ошибок.
  actual-result: |
    В консоли появляются сообщения об ошибках.
    1."GET https://site/static/js/author.js net::ERR_NAME_NOT_RESOLVED"
    2."GET https://site/static/css/random.css net::ERR_NAME_NOT_RESOLVED"

- summary: |
    При оформлении заказа появляются ошибки загрузки
  environment: |
    Google Chrome	128.0.6613.138 (Официальная сборка) (64 бит)
    ОС Windows 11
  steps-to-reproduce: |
    1. Добавить товар в корзину
    2. Перейти в корзину 
    2. Открыть DevTools 
    3. В корзине нажать кнопку "Checkout"
    4. Перейти в Console
  expected-result: |
    Заказ отправляется без ошибок.
  actual-result: |
    В консоли появляется сообщение об ошибке.
    "GET https://dummyjson.com/http/500/failed 500 (Internal Server Error)"   
    
- summary: |
    Не отображается в русской версии информации о товаре на русском языке
  environment: |
    Google Chrome	128.0.6613.138 (Официальная сборка) (64 бит)
    ОС Windows 11
  steps-to-reproduce: |
    1. Зайти на страницу магазина
    2. Нажать кнопку "Language" и выбрать "Russian" 
    3. Перейти на вкладку "Магазин"
  expected-result: |
    Отобразится в русской версии информации о товаре на русском языке.
  actual-result: |
    Информация о товаре, описание остается на английском языке.

- summary: |
    SPA-приложение перезагружает страницу при переходе из вкладки "Корзина" во вкладку "Магазин"
  environment: |
    Google Chrome	128.0.6613.138 (Официальная сборка) (64 бит)
    ОС Windows 11
  steps-to-reproduce: |
    1. Зайти на страницу магазина
    2. Перейти во вкладку "Корзина" 
    3. Перейти во вкладку "Магазин"
  expected-result: |
    SPA-приложение не перезагружает страницу
  actual-result: |
    SPA-приложение перезагружает страницу.

1- summary: |
    После просмотра карточки товара, ранее введенные фильтры не сохраняются
  environment: |
    Google Chrome	128.0.6613.138 (Официальная сборка) (64 бит)
    ОС Windows 11
  steps-to-reproduce: |
    1. Выбрать фильтры в боковой панели
    2. Зайти в карточку товара
    3. Нажать стрелку "назад" в браузере
  expected-result: |
    Сайт должен отобразить товары в соответствии с ранее установленными фильтрами
  actual-result: |
    После просмотра карточки товара, ранее введенные фильтры не сохраняются

- summary: |
    После нажатия в корзине кнопки "Continue shopping", ранее введенные фильтры не сохраняются
  environment: |
    Google Chrome	128.0.6613.138 (Официальная сборка) (64 бит)
    ОС Windows 11
  steps-to-reproduce: |
    1. Выбрать фильтры в боковой панели
    2. В корзину добавить товары 
    3. Перейти в корзину сайта магазина
    4. Нажать кнопку "Continue shopping"
  expected-result: |
    После нажатия в корзине кнопки "Continue shopping", ранее введенные фильтры сохраняются.    
  actual-result: |
    После нажатия в корзине кнопки "Continue shopping", ранее введенные фильтры не сохраняются.  

- summary: |
    Окно успешного оформления заказа не закрывается после нажатия кнопки "крестик".
  environment: |
    Google Chrome	128.0.6613.138 (Официальная сборка) (64 бит)
    ОС Windows 11
  steps-to-reproduce: |
    1. В корзину добавить товары
    2. Перейти в корзину
    3. Нажать кнопку "Сheckout"
    4. В открывшемся окне успешного оформления заказа нажать "крестик"
  expected-result: |
    Окно успешного оформления заказа должно закрыться после нажатия кнопки "крестик"   
  actual-result: |
    Окно успешного оформления заказа не закрывается после нажатия кнопки "крестик".    

- summary: |
    Возможно оформить заказ на отсутствующий товар.
  environment: |
    Google Chrome	128.0.6613.138 (Официальная сборка) (64 бит)
    ОС Windows 11
  steps-to-reproduce: |
    1. В корзину добавить товары, которых нет в наличии 
    2. Перейти в корзину
    3. Нажать кнопку "Сheckout"
  expected-result: |
    Должно появиться сообщение о невозможности оформить заказ на товар, которого нет в наличи   
  actual-result: |
    Открывается окно успешного заказа при оформлении заказа на отсутствующий товар.      
    

---
 








- summary: |
    Проверка возможности менять количество заказываемого товара в корзине
  requirement: |
    Возможно поменять количество заказываемого товара в корзине
  prerequisites: 
    В корзину добавлены товары
  test-data: |
    Открыта страница корзины сайта магазина
  steps:
    - Пытаемся поменять количество заказываемого товара
  expected-result: |
    Должны быть кнопки для увеличения и уменьшения количества заказываемого товара

- summary: |
    Проверка того, что боковая панель фильтров и шапка сайта закреплены на странице
  requirement: |
    Боковая панель фильтров и шапка сайта закреплены на странице
  prerequisites: 
    Открыта главная страница сайта
  test-data: |
    Открыта главная страница сайта
  steps:
    - Листаем страницу со списком товаров вниз
  expected-result: |
    Боковая панель фильтров и шапка сайта закреплены на странице и не уходят из "поля зрения"

