---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен иметь форму регистрации пользователя
  - Сайт должен иметь форму входа зарегистрированного пользователя
  - Сайт должен иметь русскую и английскую версии
  - Сайт должен быть SPA-приложение, которое не перезагружает страницу
  - При оформлении заказа пользователь должен указать контактные данные
  - При оформлении заказа должен произойти переход на страницу оплаты
  - Корзина должна храниться в сессии браузера
  - При выборе языка рядом с английским языком должно отображаться изображение флага англоязычной страны
  - Должна быть возможность сбросить фильтр по категории
  - При нажатии на фильтр по Категориям товаров должны отображаться все категории
  - В таблице списка товаров в корзине должны быть заголовки
