---
- summary: |
    Краткое описание тест кейса. Пример: Проверка входа пользователя с существующими логином и паролем
  requirement: |
    Тестируемое требование. Например: При верном вводе логине и пароля пользователь должен войти в систему
  prerequisites: |
    Это условия, которые необходимы для проведения тест кейса. Они должны быть выполнены еще до запуска тест кейса.
    Например: открыта страница логина
  test-data: |
    Тестовые данные
    Логин = ilona Пароль = password
  steps:
    - Вводим логин
    - Вводим пароль
    - Нажимаем кнопку "Войти"
  expected-result: |
    Пользователь должен попасть на главную страницу

- summary: |
    Проверка возможности искать товары по ключевому слову
  requirement: |
    Пользователь должен иметь возможность искать товары по ключевому слову
  prerequisites:
    Открыта главная страница сайта
  test-data: |
    Ключевое слово Apple
  steps:
    - Вводим в поле поиска ключевое слово
  expected-result: |
    Сайт должен показать товары, содержащие ключевое слово   

- summary: |
    Проверка возможности искать товары по категории
  requirement: |
    Пользователь должен иметь возможность искать товары по категории
  prerequisites:
    Открыт сайт магазина
  test-data: |
    Категория = Furniture
  steps:
    - Выбираем категорию товара
  expected-result: |
    Сайт должен показать товары из выбранной категории 

- summary: |
    Проверка возможности фильтровать товары по производителю
  requirement: |
    Пользователь должен иметь возможность фильтровать товары по производителю
  prerequisites:
    Открыт сайт магазина
  test-data: |
    Производитель = Dior
  steps:
    - Выбираем производителя товара
  expected-result: |
    Сайт должен показать товары выбранного производителя   

- summary: |
    Проверка возможности просматривать подробную информацию о товаре
  requirement: |
    Пользователь должен иметь возможность просматривать подробную информацию о товаре
  prerequisites:
    Открыт сайт магазина
  test-data: |
    Товар = Ice Cream
  steps:
    - Нажимаем на карточку товара
  expected-result: |
    Должна открыться страница с подробной информацией о товаре     

- summary: |
    Проверка возможности добавлять товары в корзину
  requirement: |
    Пользователь должен иметь возможность добавлять товары в корзину
  prerequisites:
    Открыт сайт магазина
  test-data: |
    Товар = Ice Cream
  steps:
    - Нажимаем на кнопку "В корзину"
  expected-result: |
    Выбранный товар должен быть добавлен в корзину   

- summary: |
    Проверка наличия английской версии
  requirement: |
    Сайт должен иметь английскую версию
  prerequisites:
    Открыт сайт магазина в русской версии
  test-data: |
    Язык = English
  steps:
    - Нажимаем на кнопку "Язык"
    - Выбираем "English"
  expected-result: |
    Сайт должен отобразиться на английском языке  

- summary: |
    Проверка  перехода на страницу оплаты при оформлении заказа
  requirement: |
    При оформлении заказа должен произойти переход на страницу оплаты
  prerequisites:
    Открыта страница корзины с добавленным товаром
  test-data: |
    Товар = Ice Cream
  steps:
    - Нажимаем на кнопку "Оформить заказ"
  expected-result: |
    Должен произойти переход на страницу оплаты 

- summary: |
    Проверка отображения в русской версии информации о товаре на русском языке
  requirement: |
    Пользователь должен иметь возможность в русской версии сайта просматривать информацию о товаре на русском языке
  prerequisites:
    Открыт сайт магазина в английской версии
  test-data: |
    Язык = Russian
  steps:
    - Нажимаем на кнопку "Language"
    - Выбираем "Russian"
  expected-result: |
    Сайт должен отобразить описание товаров на русском языке 

- summary: |
    Проверка того, что SPA-приложение не перезагружает страницу
  requirement: |
    Сайт должен быть SPA-приложение, которое не перезагружает страницу
  prerequisites:
    Открыта страница корзины сайта магазина
  test-data: |
    Раздел "Cart"
  steps:
    - Нажимаем на кнопку "Store"
  expected-result: |
    Сайт должен перейти в раздел "Store" без перезагрузки страницы

- summary: |
    Проверка отображения артикула в корзине без слов "шт." и "qty."
  requirement: |
    В таблице списка товаров в корзине рядом с артикулами товаров не должно быть слов "шт." и "qty."
  prerequisites:
    Открыта страница сайта магазина
  test-data: |
    Товар = Ice Cream
  steps:
    - Нажимаем на кнопку "Add to cart" в выбранном товаре
    - Нажимаем на кнопку "Cart"
  expected-result: |
    В таблице списка товаров в корзине рядом с артикулами товаров не должно быть слов "шт." и "qty."

